import Head from 'next/head';
import { useState } from 'react';

type Forecast = {
  min_temp: string;
  max_temp: string;
  pop: string;
  valid_date: string;
  weather: { description: string };
};

export default function Home() {
  const [weather, setWeather] = useState<Forecast[] | undefined>();

  async function getWeatherFromApi() {
    const weatherResponse = await fetch('/api/getWeather', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ objectId: 'O5oFGZDqPP' }),
    });
    const weatherBody = await weatherResponse.json();
    setWeather(weatherBody.weather);
    console.log('weather: ', weather);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>

        <p>Get started</p>

        <button
          onClick={() => {
            getWeatherFromApi().catch((err) => console.log(err));
          }}
        >
          get weather
        </button>
        {weather && (
          <div>
            <p>Date: {weather[0].valid_date}</p>
            <p>Min: {weather[0].min_temp}</p>
            <p>Max: {weather[0].max_temp}</p>
            <p>Precipitation: {weather[0].pop}%</p>
            <p>{weather[0].weather.description}</p>
          </div>
        )}
      </main>
    </>
  );
}
