import Head from 'next/head';
import { useEffect, useState } from 'react';
import { outdoorWorkoutStyles } from '../styles/indexStyles';

type ApiWeatherResponse = {
  weather: Forecast[];
  activityDate: { objectId: string };
  city: string;
};

type Forecast = {
  min_temp: string;
  max_temp: string;
  pop: string;
  valid_date: string;
  weather: { description: string };
};

type Workout = {
  _source: {
    description: string;
    name: string;
    activityDate: {
      start: { iso: string };
      objectId: string;
    };
    partner: { name: string };
    participationModes: string[];
    city: string;
  };
};

export default function Home() {
  const [forecast, setForecast] = useState<ApiWeatherResponse | undefined>();
  const [error, setError] = useState<string | undefined>();
  const [workouts, setWorkouts] = useState<Workout[] | undefined>();

  async function getWeatherFromApi() {
    const weatherResponse = await fetch('/api/getWeather', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ objectId: 'O5oFGZDqPP' }),
    });
    const weatherBody: { error: string } | ApiWeatherResponse =
      await weatherResponse.json();
    console.log('weatherBody', weatherBody);
    if ('error' in weatherBody) {
      setError(weatherBody.error);
      return;
    }
    setForecast(weatherBody);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>

        <p>Get started</p>

        <button
          onClick={() => {
            getWeatherFromApi().catch((err) => console.log(err));
          }}
        >
          get weather
        </button>
        {weather && (
          <div>
            <p>Date: {weather[0].valid_date}</p>
            <p>Min: {weather[0].min_temp}</p>
            <p>Max: {weather[0].max_temp}</p>
            <p>Precipitation: {weather[0].pop}%</p>
            <p>{weather[0].weather.description}</p>
          </div>
        )}
      </main>
    </>
  );
}
